export interface CountryInfo {
  name: string;
  gl: string; // ISO 2-letter country code
  hl: string; // dominant language code
}

export const COUNTRIES: CountryInfo[] = [
  { name: "Global / Multi-Region", gl: "US", hl: "en" },
  { name: "Afghanistan", gl: "AF", hl: "ps" },
  { name: "Albania", gl: "AL", hl: "sq" },
  { name: "Algeria", gl: "DZ", hl: "ar" },
  { name: "Andorra", gl: "AD", hl: "ca" },
  { name: "Angola", gl: "AO", hl: "pt" },
  { name: "Argentina", gl: "AR", hl: "es" },
  { name: "Armenia", gl: "AM", hl: "hy" },
  { name: "Australia", gl: "AU", hl: "en" },
  { name: "Austria", gl: "AT", hl: "de" },
  { name: "Azerbaijan", gl: "AZ", hl: "az" },
  { name: "Bahamas", gl: "BS", hl: "en" },
  { name: "Bahrain", gl: "BH", hl: "ar" },
  { name: "Bangladesh", gl: "BD", hl: "en" },
  { name: "Barbados", gl: "BB", hl: "en" },
  { name: "Belarus", gl: "BY", hl: "be" },
  { name: "Belgium", gl: "BE", hl: "nl" },
  { name: "Belize", gl: "BZ", hl: "en" },
  { name: "Benin", gl: "BJ", hl: "fr" },
  { name: "Bhutan", gl: "BT", hl: "dz" },
  { name: "Bolivia", gl: "BO", hl: "es" },
  { name: "Bosnia and Herzegovina", gl: "BA", hl: "bs" },
  { name: "Botswana", gl: "BW", hl: "en" },
  { name: "Brazil", gl: "BR", hl: "pt" },
  { name: "Brunei", gl: "BN", hl: "ms" },
  { name: "Bulgaria", gl: "BG", hl: "bg" },
  { name: "Burkina Faso", gl: "BF", hl: "fr" },
  { name: "Burundi", gl: "BI", hl: "fr" },
  { name: "Cambodia", gl: "KH", hl: "km" },
  { name: "Cameroon", gl: "CM", hl: "fr" },
  { name: "Canada", gl: "CA", hl: "en" },
  { name: "Cape Verde", gl: "CV", hl: "pt" },
  { name: "Central African Republic", gl: "CF", hl: "fr" },
  { name: "Chad", gl: "TD", hl: "fr" },
  { name: "Chile", gl: "CL", hl: "es" },
  { name: "China", gl: "CN", hl: "zh" },
  { name: "Colombia", gl: "CO", hl: "es" },
  { name: "Comoros", gl: "KM", hl: "ar" },
  { name: "Congo (Congo-Brazzaville)", gl: "CG", hl: "fr" },
  { name: "Costa Rica", gl: "CR", hl: "es" },
  { name: "Croatia", gl: "HR", hl: "hr" },
  { name: "Cuba", gl: "CU", hl: "es" },
  { name: "Cyprus", gl: "CY", hl: "el" },
  { name: "Czechia (Czech Republic)", gl: "CZ", hl: "cs" },
  { name: "Democratic Republic of the Congo", gl: "CD", hl: "fr" },
  { name: "Denmark", gl: "DK", hl: "da" },
  { name: "Djibouti", gl: "DJ", hl: "fr" },
  { name: "Dominica", gl: "DM", hl: "en" },
  { name: "Dominican Republic", gl: "DO", hl: "es" },
  { name: "Ecuador", gl: "EC", hl: "es" },
  { name: "Egypt", gl: "EG", hl: "ar" },
  { name: "El Salvador", gl: "SV", hl: "es" },
  { name: "Equatorial Guinea", gl: "GQ", hl: "es" },
  { name: "Eritrea", gl: "ER", hl: "ti" },
  { name: "Estonia", gl: "EE", hl: "et" },
  { name: "Eswatini (fmr. Swaziland)", gl: "SZ", hl: "en" },
  { name: "Ethiopia", gl: "ET", hl: "am" },
  { name: "Fiji", gl: "FJ", hl: "en" },
  { name: "Finland", gl: "FI", hl: "fi" },
  { name: "France", gl: "FR", hl: "fr" },
  { name: "Gabon", gl: "GA", hl: "fr" },
  { name: "Gambia", gl: "GM", hl: "en" },
  { name: "Georgia", gl: "GE", hl: "ka" },
  { name: "Germany", gl: "DE", hl: "de" },
  { name: "Ghana", gl: "GH", hl: "en" },
  { name: "Greece", gl: "GR", hl: "el" },
  { name: "Grenada", gl: "GD", hl: "en" },
  { name: "Guatemala", gl: "GT", hl: "es" },
  { name: "Guinea", gl: "GN", hl: "fr" },
  { name: "Guinea-Bissau", gl: "GW", hl: "pt" },
  { name: "Guyana", gl: "GY", hl: "en" },
  { name: "Haiti", gl: "HT", hl: "fr" },
  { name: "Honduras", gl: "HN", hl: "es" },
  { name: "Hungary", gl: "HU", hl: "hu" },
  { name: "Iceland", gl: "IS", hl: "is" },
  { name: "India", gl: "IN", hl: "en" },
  { name: "Indonesia", gl: "ID", hl: "id" },
  { name: "Iran", gl: "IR", hl: "fa" },
  { name: "Iraq", gl: "IQ", hl: "ar" },
  { name: "Ireland", gl: "IE", hl: "en" },
  { name: "Israel", gl: "IL", hl: "he" },
  { name: "Italy", gl: "IT", hl: "it" },
  { name: "Ivory Coast", gl: "CI", hl: "fr" },
  { name: "Jamaica", gl: "JM", hl: "en" },
  { name: "Japan", gl: "JP", hl: "ja" },
  { name: "Jordan", gl: "JO", hl: "ar" },
  { name: "Kazakhstan", gl: "KZ", hl: "kk" },
  { name: "Kenya", gl: "KE", hl: "sw" },
  { name: "Kiribati", gl: "KI", hl: "en" },
  { name: "Kuwait", gl: "KW", hl: "ar" },
  { name: "Kyrgyzstan", gl: "KG", hl: "ky" },
  { name: "Laos", gl: "LA", hl: "lo" },
  { name: "Latvia", gl: "LV", hl: "lv" },
  { name: "Lebanon", gl: "LB", hl: "ar" },
  { name: "Lesotho", gl: "LS", hl: "en" },
  { name: "Liberia", gl: "LR", hl: "en" },
  { name: "Libya", gl: "LY", hl: "ar" },
  { name: "Liechtenstein", gl: "LI", hl: "de" },
  { name: "Lithuania", gl: "LT", hl: "lt" },
  { name: "Luxembourg", gl: "LU", hl: "fr" },
  { name: "Madagascar", gl: "MG", hl: "mg" },
  { name: "Malawi", gl: "MW", hl: "en" },
  { name: "Malaysia", gl: "MY", hl: "ms" },
  { name: "Maldives", gl: "MV", hl: "dv" },
  { name: "Mali", gl: "ML", hl: "fr" },
  { name: "Malta", gl: "MT", hl: "mt" },
  { name: "Marshall Islands", gl: "MH", hl: "en" },
  { name: "Mauritania", gl: "MR", hl: "ar" },
  { name: "Mauritius", gl: "MU", hl: "en" },
  { name: "Mexico", gl: "MX", hl: "es" },
  { name: "Micronesia", gl: "FM", hl: "en" },
  { name: "Moldova", gl: "MD", hl: "ro" },
  { name: "Monaco", gl: "MC", hl: "fr" },
  { name: "Mongolia", gl: "MN", hl: "mn" },
  { name: "Montenegro", gl: "ME", hl: "sr" },
  { name: "Morocco", gl: "MA", hl: "ar" },
  { name: "Mozambique", gl: "MZ", hl: "pt" },
  { name: "Myanmar (formerly Burma)", gl: "MM", hl: "my" },
  { name: "Namibia", gl: "NA", hl: "en" },
  { name: "Nauru", gl: "NR", hl: "en" },
  { name: "Nepal", gl: "NP", hl: "ne" },
  { name: "Netherlands", gl: "NL", hl: "nl" },
  { name: "New Zealand", gl: "NZ", hl: "en" },
  { name: "Nicaragua", gl: "NI", hl: "es" },
  { name: "Niger", gl: "NE", hl: "fr" },
  { name: "Nigeria", gl: "NG", hl: "en" },
  { name: "North Korea", gl: "KP", hl: "ko" },
  { name: "North Macedonia", gl: "MK", hl: "mk" },
  { name: "Norway", gl: "NO", hl: "no" },
  { name: "Oman", gl: "OM", hl: "ar" },
  { name: "Pakistan", gl: "PK", hl: "ur" },
  { name: "Palau", gl: "PW", hl: "en" },
  { name: "Palestine State", gl: "PS", hl: "ar" },
  { name: "Panama", gl: "PA", hl: "es" },
  { name: "Papua New Guinea", gl: "PG", hl: "en" },
  { name: "Paraguay", gl: "PY", hl: "es" },
  { name: "Peru", gl: "PE", hl: "es" },
  { name: "Philippines", gl: "PH", hl: "en" },
  { name: "Poland", gl: "PL", hl: "pl" },
  { name: "Portugal", gl: "PT", hl: "pt" },
  { name: "Qatar", gl: "QA", hl: "ar" },
  { name: "Romania", gl: "RO", hl: "ro" },
  { name: "Russia", gl: "RU", hl: "ru" },
  { name: "Rwanda", gl: "RW", hl: "rw" },
  { name: "Saint Kitts and Nevis", gl: "KN", hl: "en" },
  { name: "Saint Lucia", gl: "LC", hl: "en" },
  { name: "Saint Vincent and the Grenadines", gl: "VC", hl: "en" },
  { name: "Samoa", gl: "WS", hl: "sm" },
  { name: "San Marino", gl: "SM", hl: "it" },
  { name: "Sao Tome and Principe", gl: "ST", hl: "pt" },
  { name: "Saudi Arabia", gl: "SA", hl: "ar" },
  { name: "Senegal", gl: "SN", hl: "fr" },
  { name: "Serbia", gl: "RS", hl: "sr" },
  { name: "Seychelles", gl: "SC", hl: "en" },
  { name: "Sierra Leone", gl: "SL", hl: "en" },
  { name: "Singapore", gl: "SG", hl: "en" },
  { name: "Slovakia", gl: "SK", hl: "sk" },
  { name: "Slovenia", gl: "SI", hl: "sl" },
  { name: "Solomon Islands", gl: "SB", hl: "en" },
  { name: "Somalia", gl: "SO", hl: "so" },
  { name: "South Africa", gl: "ZA", hl: "en" },
  { name: "South Korea", gl: "KR", hl: "ko" },
  { name: "South Sudan", gl: "SS", hl: "en" },
  { name: "Spain", gl: "ES", hl: "es" },
  { name: "Sri Lanka", gl: "LK", hl: "si" },
  { name: "Sudan", gl: "SD", hl: "ar" },
  { name: "Suriname", gl: "SR", hl: "nl" },
  { name: "Sweden", gl: "SE", hl: "sv" },
  { name: "Switzerland", gl: "CH", hl: "de" },
  { name: "Syria", gl: "SY", hl: "ar" },
  { name: "Tajikistan", gl: "TJ", hl: "tg" },
  { name: "Tanzania", gl: "TZ", hl: "sw" },
  { name: "Thailand", gl: "TH", hl: "th" },
  { name: "Timor-Leste", gl: "TL", hl: "pt" },
  { name: "Togo", gl: "TG", hl: "fr" },
  { name: "Tonga", gl: "TO", hl: "to" },
  { name: "Trinidad and Tobago", gl: "TT", hl: "en" },
  { name: "Tunisia", gl: "TN", hl: "ar" },
  { name: "Turkey", gl: "TR", hl: "tr" },
  { name: "Turkmenistan", gl: "TM", hl: "tk" },
  { name: "Tuvalu", gl: "TV", hl: "en" },
  { name: "Uganda", gl: "UG", hl: "en" },
  { name: "Ukraine", gl: "UA", hl: "uk" },
  { name: "United Arab Emirates", gl: "AE", hl: "ar" },
  { name: "United Kingdom", gl: "GB", hl: "en" },
  { name: "United States", gl: "US", hl: "en" },
  { name: "Uruguay", gl: "UY", hl: "es" },
  { name: "Uzbekistan", gl: "UZ", hl: "uz" },
  { name: "Vanuatu", gl: "VU", hl: "bi" },
  { name: "Venezuela", gl: "VE", hl: "es" },
  { name: "Vietnam", gl: "VN", hl: "vi" },
  { name: "Yemen", gl: "YE", hl: "ar" },
  { name: "Zambia", gl: "ZM", hl: "en" },
  { name: "Zimbabwe", gl: "ZW", hl: "en" }
];

export function getCountryLocale(name: string): { hl: string; gl: string } {
  const normName = name.trim().toLowerCase();
  
  // Quick match
  if (normName === "global" || normName === "global / multi-region") {
    return { hl: "en", gl: "US" };
  }
  
  const found = COUNTRIES.find(c => c.name.toLowerCase() === normName);
  if (found) {
    return { hl: found.hl, gl: found.gl };
  }
  
  // Partial fuzzy matching
  const fuzzy = COUNTRIES.find(c => c.name.toLowerCase().includes(normName) || normName.includes(c.name.toLowerCase()));
  if (fuzzy) {
    return { hl: fuzzy.hl, gl: fuzzy.gl };
  }
  
  return { hl: "en", gl: "US" };
}
